[package]
name = "walltaker-rust"
version = "0.3.2"
edition = "2021"

[dependencies]
tokio = {version = "1.43.0", features = ["full"]}
toml = "0.8.20"
json = "0.12.4"
reqwest = "0.12.15"
more-wallpapers = "0.4.0"
