[package]
name = "walltaker-rust"
version = "0.1.1"
edition = "2021"

[dependencies]
json = "0.12.4"
more-wallpapers = "0.4.0"
reqwest = {version=  "0.12.12", features = ["json"]}
tokio = {version = "1.43.0", features = ["full"]}
